In [2]:
from scipy.integrate import dblquad
import numpy as np

In [3]:
#Esta funcion reproduce el calculo de Graff(2013) para la evidencia del eggbox
def EggboxFunc1(y,x):
    return ((1/(10*np.pi))**2)*np.exp((2 + np.cos(x/2)*np.cos(y/2))**5)

int1 = dblquad(EggboxFunc1, 0, 10*np.pi, lambda x: 0, lambda x: 10*np.pi)
np.log(int1[0])
#dblquad(f, 0, y_max, lambda x: 0, lambda x: x_max)

235.85594033225414

In [9]:
tmax = 5.0 * np.pi
constant = np.log(1.0 / tmax**2)

def eggLoglike(y,x):
    t1 = 2.0 * tmax * y - tmax
    t2 = 2.0 * tmax * x - tmax
    a = (2.0 + np.cos(t2/2.0)*np.cos(t1/2.0))**5.0
    return np.exp(-(2.0 + np.cos(t2/2.0)*np.cos(t1/2.0))**5.0)

int2 = dblquad(eggLoglike, 0, 1, lambda x: 0, lambda x: 1)
np.log(int2)

array([ -4.16416448, -18.03754271])

In [11]:
def himmelLoglike(y,x):
    return np.exp(-(x**2+y-11)**2.0-(x+y**2-7)**2)*((1/10)**2)

int3 = dblquad(himmelLoglike, -5, 5, lambda x: -5, lambda x: 5)
np.log(int3)

array([ -5.50384972, -18.02820282])

In [14]:
def ringLoglike(y,x):
    r2=x**2+y**2
    return np.exp(-(r2-4.0)**2/(2*0.5**2))*((1/10)**2)


int4 = dblquad(ringLoglike, -5, 5, lambda x: -5, lambda x: 5)
np.log(int4)

array([ -3.23464895, -18.03780583])

In [16]:
def gaussLoglike(y,x):
        return np.exp(-((x)**2+(y)**2/2.0 - 1.0*x*y)/2.0)*((1/10)**2)


int5 = dblquad(gaussLoglike, -5, 5, lambda x: -5, lambda x: 5)
np.log(int5)

array([ -2.08681004, -18.41738485])

In [17]:
def squareLoglike(y,x):
    sq = 1.
    if abs(x)>5 or abs(y)>5:
        sq = 0.
    return np.exp(sq)*((1/10)**2)


int5 = dblquad(squareLoglike, -5, 5, lambda x: -5, lambda x: 5)
np.log(int5)


array([  1.        , -31.13163038])